### ISSUE TITLE
CRBT doesn't recognize forum channels in /server info

### ISSUE THREAD

**Issue by user5522** [Clembs/CRBT#7]
title says it all, here is a picture

![image](https://user-images.githubusercontent.com/65370936/217246069-c960b8e7-d499-4427-990d-3c02b0aa0ae0.png)
![image](https://user-images.githubusercontent.com/65370936/217246176-39f7933e-d60d-4566-b88d-4797acb0e8a4.png)

I would've done a pull request but I have no idea how purplet works (unfortunate)

**Comment by clembs** [comment]
that's a pretty easy fix, i'll probably push this soon

**Comment by clembs** [comment]
It's now available!
![image](https://user-images.githubusercontent.com/67973777/225948584-4bd50389-894f-421f-bb18-9f7aee98d831.png)
